run_configurations:
  "direct":
    sbatch_config:
      "nodes": 1
      "ntasks-per-node": 1
      "cpus-per-task": 1
      "exclusive": "mcs"
      "mem": 60000
    module_loads: []
    environment_variables: {}
    directory: "./generated_results/hpccg-rs-kudu-results/hpccg-rs/1_naive"
    build_commands:
      - "cargo build --release"
    run_command: "./target/release/hpccg-rs"
    post_commands:
      - "scc src/"

  "indexed":
    sbatch_config:
      "nodes": 1
      "ntasks-per-node": 1
      "cpus-per-task": 1
      "exclusive": "mcs"
      "mem": 60000
    module_loads: []
    environment_variables: {}
    directory: "./generated_results/hpccg-rs-kudu-results/hpccg-rs/2_indexed"
    build_commands:
      - "cargo build --release"
    run_command: "./target/release/hpccg-rs"
    post_commands:
      - "scc src/"

  "single-indexed":
    sbatch_config:
      "nodes": 1
      "ntasks-per-node": 1
      "cpus-per-task": 1
      "exclusive": "mcs"
      "mem": 60000
    module_loads: []
    environment_variables: {}
    directory: "./generated_results/hpccg-rs-kudu-results/hpccg-rs/3_single_indexed"
    build_commands:
      - "cargo build --release"
    run_command: "./target/release/hpccg-rs"
    post_commands:
      - "scc src/"

  "no-bounds-check":
    sbatch_config:
      "nodes": 1
      "ntasks-per-node": 1
      "cpus-per-task": 1
      "exclusive": "mcs"
      "mem": 60000
    module_loads: []
    environment_variables: {}
    directory: "./generated_results/hpccg-rs-kudu-results/hpccg-rs/4_no_bounds_check"
    build_commands:
      - "cargo build --release"
    run_command: "./target/release/hpccg-rs"
    post_commands:
      - "scc src/"

  "iterators":
    sbatch_config:
      "nodes": 1
      "ntasks-per-node": 1
      "cpus-per-task": 1
      "exclusive": "mcs"
      "mem": 60000
    module_loads: []
    environment_variables: {}
    directory: "./generated_results/hpccg-rs-kudu-results/hpccg-rs/5_iterators"
    build_commands:
      - "cargo build --release"
    run_command: "./target/release/hpccg-rs"
    post_commands:
      - "scc src/"

  "parallel":
    sbatch_config:
      "nodes": 1
      "ntasks-per-node": 1
      "cpus-per-task": 32
      "exclusive": "mcs"
      "mem": 60000
    module_loads: []
    environment_variables: {}
    directory: "./generated_results/hpccg-rs-kudu-results/hpccg-rs/6_parallel"
    build_commands:
      - "cargo build --release"
    run_command: "./target/release/hpccg-rs"
    post_commands:
      - "scc src/"

  "mpi":
    sbatch_config:
      # "nodes": 1
      # "ntasks-per-node": 4
      # "cpus-per-task": 10
      "nodes": 2
      "ntasks-per-node": 16
      "cpus-per-task": 2
      "exclusive": "mcs"
      "mem": 60000
    module_loads:
      - "cs402-mpi"
    environment_variables: {}
    directory: "./generated_results/hpccg-rs-kudu-results/hpccg-rs/7_mpi"
    build_commands:
      - "cargo build --release"
    run_command: "mpirun ./target/release/hpccg-rs"
    post_commands:
      - "scc src/"

  "hybrid":
    sbatch_config:
      "nodes": 2
      "ntasks-per-node": 2
      "cpus-per-task": 20
      "exclusive": "mcs"
      "mem": 60000
    module_loads:
      - "cs402-mpi"
    environment_variables: {}
    directory: "./generated_results/hpccg-rs-kudu-results/hpccg-rs/8_hybrid"
    build_commands:
      - "cargo build --release"
    run_command: "mpirun ./target/release/hpccg-rs"
    post_commands:
      - "scc src/"

  "cpp-reference":
    sbatch_config:
      "nodes": 1
      "ntasks-per-node": 1
      "cpus-per-task": 1
      "exclusive": "mcs"
      "mem": 60000
    module_loads: []
    environment_variables: {}
    directory: "./generated_results/hpccg-rs-kudu-results/hpccg-rs/0_cpp_versions/9_unifdef/0_ref"
    build_commands:
      - "make no_yaml"
      - "make -j 8"
    run_command: "./test_HPCCG"
    post_commands:
      - "scc ./"

  "cpp-openmp":
    sbatch_config:
      "nodes": 1
      "ntasks-per-node": 1
      "cpus-per-task": 32
      "exclusive": "mcs"
      "mem": 60000
    module_loads: []
    environment_variables: {}
    directory: "./generated_results/hpccg-rs-kudu-results/hpccg-rs/0_cpp_versions/9_unifdef/1_openmp"
    build_commands:
      - "make no_yaml"
      - "make -j 8"
    run_command: "./test_HPCCG"
    post_commands:
      - "scc ./"

  "cpp-mpi":
    sbatch_config:
      # "nodes": 1
      # "ntasks-per-node": 4
      # "cpus-per-task": 10
      "nodes": 2
      "ntasks-per-node": 16
      "cpus-per-task": 2
      "exclusive": "mcs"
      "mem": 60000
    module_loads:
      - "cs402-mpi"
    environment_variables: {}
    directory: "./generated_results/hpccg-rs-kudu-results/hpccg-rs/0_cpp_versions/9_unifdef/2_mpi"
    build_commands:
      - "make no_yaml"
      - "make -j 8"
    run_command: "mpirun ./test_HPCCG"
    post_commands:
      - "scc ./"

  "cpp-hybrid":
    sbatch_config:
      "nodes": 2
      "ntasks-per-node": 2
      "cpus-per-task": 20
      "exclusive": "mcs"
      "mem": 60000
    module_loads:
      - "cs402-mpi"
    environment_variables: {}
    directory: "./generated_results/hpccg-rs-kudu-results/hpccg-rs/0_cpp_versions/9_unifdef/3_hybrid"
    build_commands:
      - "make no_yaml"
      - "make -j 8"
    run_command: "mpirun ./test_HPCCG"
    post_commands:
      - "scc ./"


benches:
  "productivity-performance":
    run_configurations:
      - "iterators"
      - "parallel"
      - "mpi"
      - "cpp-reference"
      - "cpp-openmp"
      - "cpp-mpi"
    reruns:
      number: 5
      highest_discard: 1
      unaggregatable_metrics:
        - "Mesh x size"
        - "Mesh y size"
        - "Mesh z size"
        - "Mesh size"
        - "Estimated development cost"
        - "Estimated development time"
    matrix:
      args:
        - "200 200 200"
    analysis:
      metrics:
        "Mesh x size": "nx: (\\d+)"
        "Mesh y size": "ny: (\\d+)"
        "Mesh z size": "nz: (\\d+)"
        "Total time (s)": "Time Summary:[\\s\\S]*Total\\s*: ([\\d\\.]+)[\\s\\S]*\nFLOPS Summary"
        "ddot time (s)": "Time Summary:[\\s\\S]*DDOT\\s*: ([\\d\\.]+)[\\s\\S]*\nFLOPS Summary"
        "waxpby time (s)": "Time Summary:[\\s\\S]*WAXPBY\\s*: ([\\d\\.]+)[\\s\\S]*\nFLOPS Summary"
        "sparsemv time (s)": "Time Summary:[\\s\\S]*SPARSEMV\\s*: ([\\d\\.]+)[\\s\\S]*\nFLOPS Summary"
        "Wall time (s)": "real\\s([\\d\\.]+)\nuser"
        "Estimated development cost": "Estimated Cost to Develop \\(organic\\) \\$([\\d,]+)"
        "Estimated development time": "Estimated Schedule Effort \\(organic\\) ([\\d\\.]+) months"
      derived_metrics:
        "Mesh size": "int(metrics['Mesh x size']) * int(metrics['Mesh y size']) * int(metrics['Mesh z size'])"
      line_plots:
        - title: "Cost / Performance Plot"
          x: "Estimated development cost"
          y: "Total time (s)"
          fix_metrics:
            "Mesh x size": "200"
        - title: "Development Time / Cost Plot"
          x: "Estimated development cost"
          y: "Total time (s)"
          fix_metrics:
            "Mesh x size": "200"
